spring.application.name=DesafioBiblioteca

spring.datasource.url=jdbc:mysql://localhost:3306/bibliotecaretomada
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ZmNkMzM0NjA5M2Y3YmFjMzEzY2M2NmRhODIxY2Q4MWY3MjkzNTE0MWQ5YzUwMzRlOTJiYTYzNzMxNmQ3NTgzZA==
jwt.expiration=86400000

server.port=8080